openapi: 3.0.0
info:
  title: Financial Resume Engine API
  version: 1.0.0
  description: API para gestionar transacciones financieras y generar reportes

servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo
  - url: https://internal-api.niloft.com
    description: Servidor de producción

components:
  securitySchemes:
    CallerId:
      type: apiKey
      in: header
      name: x-caller-id

  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
        amount:
          type: number
          format: float
        description:
          type: string
        date:
          type: string
          format: date-time
        category_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    FinancialReport:
      type: object
      properties:
        total_income:
          type: number
          format: float
        total_expenses:
          type: number
          format: float
        balance:
          type: number
          format: float
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'

paths:
  /transactions:
    get:
      summary: Obtener todas las transacciones del usuario
      security:
        - CallerId: []
      responses:
        '200':
          description: Lista de transacciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor

    post:
      summary: Crear una nueva transacción
      security:
        - CallerId: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transacción creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor

  /transactions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: ID de la transacción

    get:
      summary: Obtener una transacción específica
      security:
        - CallerId: []
      responses:
        '200':
          description: Detalles de la transacción
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: No autorizado
        '404':
          description: Transacción no encontrada
        '500':
          description: Error interno del servidor

    put:
      summary: Actualizar una transacción
      security:
        - CallerId: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transacción actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado
        '404':
          description: Transacción no encontrada
        '500':
          description: Error interno del servidor

    delete:
      summary: Eliminar una transacción
      security:
        - CallerId: []
      responses:
        '200':
          description: Transacción eliminada
        '401':
          description: No autorizado
        '404':
          description: Transacción no encontrada
        '500':
          description: Error interno del servidor

  /categories:
    get:
      summary: Obtener todas las categorías
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '500':
          description: Error interno del servidor

    post:
      summary: Crear una nueva categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: Categoría creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Error en la solicitud
        '500':
          description: Error interno del servidor

  /categories/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: ID de la categoría

    put:
      summary: Actualizar una categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: Categoría actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Error en la solicitud
        '404':
          description: Categoría no encontrada
        '500':
          description: Error interno del servidor

    delete:
      summary: Eliminar una categoría
      responses:
        '200':
          description: Categoría eliminada
        '404':
          description: Categoría no encontrada
        '500':
          description: Error interno del servidor

  /reports:
    get:
      summary: Generar reporte financiero
      security:
        - CallerId: []
      parameters:
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Fecha de inicio del reporte (YYYY-MM-DD)
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Fecha de fin del reporte (YYYY-MM-DD)
      responses:
        '200':
          description: Reporte financiero generado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialReport'
        '400':
          description: Error en los parámetros
        '401':
          description: No autorizado
        '500':
          description: Error interno del servidor 