# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Install nancy
      run: go install github.com/sonatype-nexus-community/nancy@latest

    - name: Verify dependencies
      run: go mod verify

    - name: Check for vulnerabilities
      run: go list -json -m all | nancy sleuth

    - name: Check code formatting
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted. Please run 'gofmt -w .'"
          gofmt -l .
          exit 1
        fi

    - name: Run golint
      run: golint ./...

    - name: Run govet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Run tests with coverage
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.out
